### PR TITLE
Fix auth policy guardrails 

### LINKED ISSUE #1225: Credential provider was not enabled error with AWS Bedrock guardrail
Tested on 1.0.0-alpha.4

LLM config 

```
export OPENAI_API_KEY=${OPENAI_API_KEY:-<insert your API key>}

kubectl apply -f- <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: agentgateway-system
type: Opaque
stringData:
  Authorization: $OPENAI_API_KEY
EOF

kubectl apply -f- <<EOF
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: openai
  namespace: agentgateway-system
spec:
  ai:
    provider:
      openai:
        model: gpt-3.5-turbo
  policies:
    auth:
      secretRef:
        name: openai-secret
EOF

kubectl apply -f- <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openai
  namespace: agentgateway-system
spec:
  parentRefs:
    - name: agentgateway-proxy
      namespace: agentgateway-system
  rules:
    - backendRefs:
      - name: openai
        namespace: agentgateway-system
        group: agentgateway.dev
        kind: AgentgatewayBackend
EOF
```

Policy config: 
```
kubectl create secret generic aws-secret \
  -n agentgateway-system \
  --from-literal=accessKey="$AWS_ACCESS_KEY_ID" \
  --from-literal=secretKey="$AWS_SECRET_ACCESS_KEY" \
  --from-literal=sessionToken="$AWS_SESSION_TOKEN" \
  --type=Opaque \
  --dry-run=client -o yaml | kubectl apply -f -

kubectl apply -f - <<EOF
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: openai-prompt-guard
  namespace: agentgateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: openai
  backend:
    ai:
      promptGuard:
        request:
        - bedrockGuardrails:
            identifier: <ID>
            version: "DRAFT" 
            region: us-east-1
            policies:
              auth:
                aws: 
                  secretRef:
                    name: aws-secret
        response:
        - bedrockGuardrails:
            identifier: <ID>
            version: "DRAFT" 
            region: us-east-1
            policies:
              auth:
                aws: 
                  secretRef:
                    name: aws-secret
EOF

curl "localhost:8080/v1/chat/completions" -H content-type:application/json  -d '{
 "model": "",
 "messages": [
   {
     "role": "user",
     "content": "My email is test@company.io"
   }
 ]
}' | jq

```

Result: 
```
processing failed: prompt guard failed
```

In the logs I see 
```
2026-03-13T16:22:07.546112Z	warn	llm	failed to call prompt guard webhook: backend authentication failed: the credential provider was not enabled	
2026-03-13T16:22:07.546186Z	info	request gateway=agentgateway-system/agentgateway-proxy listener=http route=agentgateway-system/openai endpoint=api.openai.com:443 src.addr=127.0.0.1:37904 http.method=POST http.host=localhost http.path=/v1/chat/completions http.version=HTTP/1.1 http.status=503 protocol=llm error="processing failed: prompt guard failed" reason=Internal duration=1ms

```

### PR DESCRIPTION
**Pull request by npolshakova**
Fixes https://github.com/agentgateway/agentgateway/issues/1225

### CODE REVIEW

File: crates/agentgateway/src/llm/policy/tests.rs [hunk 1]
```diff
@@ -1013,3 +1013,51 @@ mod prompt_guard_config_tests {
...
+	// User-provided policies come first so they take precedence, then fallback to implicit auth
+	let mut pols: Vec<BackendPolicy> = user_policies.iter().cloned().collect();
+	pols.push(BackendPolicy::BackendTLS(
+		crate::http::backendtls::SYSTEM_TRUST.clone(),
+	));
+	pols.push(BackendPolicy::BackendAuth(BackendAuth::Aws(
+		AwsAuth::Implicit {},
+	)));
+
+	// First auth in the vector wins (first-wins semantics from binds.rs)
```
Comment (howardjohn) [inline crates/agentgateway/src/llm/policy/tests.rs]: This is not a great test since its making an untested assumption the real code will handle the vec like this. Which it might or might not

**Review by howardjohn — APPROVED** [review]

File: crates/agentgateway/src/llm/policy/tests.rs (hunk 1 above)
Comment (npolshakova) [reply crates/agentgateway/src/llm/policy/tests.rs]: Yeah, actually let me refactor it a little so we can test the behavior directly

Comment (npolshakova) [reply crates/agentgateway/src/llm/policy/tests.rs]: Okay added build_request_policies to share the policy building logic

**Review by howardjohn — APPROVED** [review]
