### PR TITLE
Agentgateway vNext

### LINKED ISSUE #142: Failed to connect target: No such file or directory (os error 2)
With the config below, I'm running the agentgateway on EC2. 

```
{
  "type": "static",
  "listeners": [
    {
      "name": "sse",
      "protocol": "MCP",
      "sse": {
        "address": "[::]",
        "port": 3000
      }
    }
  ],
  "targets": {
    "mcp": [
      {
        "name": "everything",
        "stdio": {
          "cmd": "npx",
          "args": [
            "@modelcontextprotocol/server-everything"
          ]
        }
      }
    ]
  }
}
```

I'm facing error below when I tried to connect with MCP inspector, in agentgateway.

```
ubuntu@ip-10-1-25-79:~$ agentgateway -f config.json
2025-05-30T08:09:20.484689Z  INFO agentgateway: Reading config from file: config.json
2025-05-30T08:09:20.485305Z  INFO insert_target: agentgateway::xds: inserted target: everything
2025-05-30T08:09:20.485321Z  INFO agentgateway::r#static: local config initialized num_mcp_targets=1 num_a2a_targets=0
2025-05-30T08:09:20.485505Z  INFO agentgateway::inbound: serving sse on [::]:3000
2025-05-30T08:09:26.623404Z  INFO agentgateway::sse: new client message for /sse session_id="acb95df9-92aa-4a36-8c3e-3717a5051759" Request(JsonRpcRequest { jsonrpc: JsonRpcVersion2_0, id: Number(0), request: InitializeRequest(Request { method: InitializeResultMethod, params: InitializeRequestParam { protocol_version: ProtocolVersion("2025-03-26"), capabilities: ClientCapabilities { experimental: None, roots: Some(RootsCapabilities { list_changed: Some(true) }), sampling: Some({}) }, client_info: Implementation { name: "mcp-inspector", version: "0.13.0" } }, extensions: Extensions }) })
2025-05-30T08:09:26.623624Z ERROR agentgateway::relay::pool: Failed to connect target everything: No such file or directory (os error 2)
2025-05-30T08:09:26.623667Z ERROR agentgateway::sse: serving error: Custom { kind: Other, error: "initialize failed: -32603: Failed to list connections: No such file or directory (os error 2)" }
2025-05-30T08:09:26.623672Z ERROR agentgateway::sse: initialize error error=Custom { kind: Other, error: "initialize failed: -32603: Failed to list connections: No such file or directory (os error 2)" }
```

The MCP inspector logs (terminal logs) are as below.

```
New SSE connection. NOTE: The sse transport is deprecated and has been replaced by streamable-http
Query parameters: [Object: null prototype] {
  url: 'http://10.1.25.79:3000/sse',
  transportType: 'sse'
}
SSE transport: url=http://10.1.25.79:3000/sse, headers=Accept
Connected to SSE transport
Connected MCP client to backing server transport
Created web app transport
Set up MCP proxy
Received message for sessionId 8d2ee68b-6d2e-4e49-bfa1-cb7595796f5c
Error from MCP server: SseError: SSE error: undefined
    at _eventSource.onerror (file:///Users/piljae/.npm/_npx/5a9d879542beca3a/node_modules/@modelcontextprotocol/sdk/dist/esm/client/sse.js:70:31)
    at EventSource.scheduleReconnect_fn (file:///Users/piljae/.npm/_npx/5a9d879542beca3a/node_modules/eventsource/dist/index.js:248:53)
    at file:///Users/piljae/.npm/_npx/5a9d879542beca3a/node_modules/eventsource/dist/index.js:95:219
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: undefined,
  event: {
    type: 'error',
    message: undefined,
    code: undefined,
    defaultPrevented: false,
    cancelable: false,
    timeStamp: 4013363.869166
  }
}
```

Are there anything I'm missing?

### LINKED ISSUE #144: Support for StreamableHTTP Transport Mode in Target Configuration
Right now, I only see `SSE`, `stdio` and `OpenAPI` transport mode while configuring a target.

Image

Is there a plan to support StreamableHTTP target type anytime soon?

We have a use case that involves running multiple instances of MCP servers running in a k8s cluster. With SSE, we’re facing challenges related to session persistence—requests may be routed to pods that do not have the necessary session state, leading to failures. With the introduction of StreamableHTTP transport https://github.com/modelcontextprotocol/modelcontextprotocol/pull/206, it is possible to create stateless MCP servers which helps in horizontally scaling MCP servers.

### LINKED ISSUE #148: npx does not work in dockerfile
After fixing up dockerfile with 

# For persistent volume for config folder
VOLUME ["/root/.config/agentgateway"]

# Exposing ports for UI and a range for listeners
EXPOSE 19000-19100

# Logs

2025-06-15T22:28:59.817968Z  INFO agentgateway: Reading config from cache_dir: /root/.config/agentgateway/config.json

2025-06-15T22:28:59.818891Z  INFO agentgateway::r#static: local config initialized num_mcp_targets=0 num_a2a_targets=0

2025-06-15T22:29:25.734730Z  INFO agentgateway::inbound: serving sse on 0.0.0.0:19001

2025-06-15T22:29:39.732669Z  INFO insert_target: agentgateway::xds: inserted target: everything

2025-06-15T22:29:45.898793Z  INFO agentgateway::sse: sse connection session=4caad444-7c8f-4912-a9db-3644c81f802b connection=Address { addr: 192.168.65.1:25446, identity: None }

2025-06-15T22:29:45.905027Z  INFO agentgateway::sse: new client message for /sse session_id="4caad444-7c8f-4912-a9db-3644c81f802b" Request(JsonRpcRequest { jsonrpc: JsonRpcVersion2_0, id: Number(0), request: InitializeRequest(Request { method: InitializeResultMethod, params: InitializeRequestParam { protocol_version: ProtocolVersion("2024-11-05"), capabilities: ClientCapabilities { experimental: None, roots: None, sampling: None }, client_info: Implementation { name: "agentgateway-dashboard", version: "0.1.0" } }, extensions: Extensions }) })

2025-06-15T22:29:45.905372Z ERROR agentgateway::relay::pool: Failed to connect target everything: No such file or directory (os error 2)

2025-06-15T22:29:45.905400Z ERROR agentgateway::sse: serving error: Custom { kind: Other, error: "initialize failed: -32603: Failed to list connections: No such file or directory (os error 2)" }

2025-06-15T22:29:45.905407Z ERROR agentgateway::sse: initialize error error=Custom { kind: Other, error: "initialize failed: -32603: Failed to list connections: No such file or directory (os error 2)" }

# Other Notes
Tried to docker exec into the container to examine if npm was installed correctly, but could not find a shell program in the path.

Also note tried npx on run of binary straight on the Mac. After reinstalling node and relaxing security(npm config set strict-ssl false), quickstart exampled worked fine.

# Research

Based on the comand in the dockerfile -> FROM gcr.io/distroless/cc-debian12 AS runner 

"Distroless" images contain only your application and its runtime dependencies. They do not contain package managers, shells or any other programs you would expect to find in a standard Linux distribution.

No shell exists, thus npm can not run, thus npx will not work.  Maybe pick a different OS variant?

# The Answer to the problem

Changed the OS which includes a shell and SUCCESS

# New dockerfile

FROM docker.io/library/node:23.11.0-bookworm AS node

WORKDIR /app

COPY ui .

RUN npm install

RUN npm run build

FROM docker.io/library/rust:1.86.0-slim-bookworm AS builder 

ARG TARGETARCH

RUN apt-get update && apt-get install -y --no-install-recommends \
    protobuf-compiler make libssl-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Makefile Cargo.toml Cargo.lock ./
COPY crates ./crates
COPY common ./common
COPY --from=node /app/out ./ui/out
RUN --mount=type=cache,id=cargo,target=/usr/local/cargo/registry cargo fetch --locked
RUN --mount=type=cache,id=cargo,target=/usr/local/cargo/registry make build

RUN strip target/release/agentgateway

#FROM gcr.io/distroless/cc-debian12 AS runner 
#Using bookworm for an easy filx
FROM docker.io/library/node:23.11.0-bookworm AS runner

ARG TARGETARCH
WORKDIR /app

COPY --from=builder /app/target/release/agentgateway /app/agentgateway

LABEL org.opencontainers.image.source=https://github.com/agentgateway/agentgateway
LABEL org.opencontainers.image.description="Agent Gateway is an agentic network gateway."

VOLUME ["/root/.config/agentgateway"]

EXPOSE 19000-19100

ENTRYPOINT ["/app/agentgateway"]

-----------------------------------

Please review, close, and adopt changes to the dockerfile in the respository.

### LINKED ISSUE #149: OpenAPI yaml and Go protobuf stubs are out of sync
The repository contains updated `.proto` files and source code, but the generated protobuf stubs/clients and OpenAPI yaml are not up to date with these changes. This creates inconsistencies between the protocol definitions and the generated artifacts.

We are trying to integrate `agentgateway` with our existing control-plane that we use to manage other gateways, but we cannot proceed with either xDS or REST API integration due to the outdated generated files.

## Example: RBAC section inconsistency
The RBAC (Role-Based Access Control) section demonstrates this issue:

- `.proto files`: Contain updated RBAC [message definitions](https://github.com/agentgateway/agentgateway/blob/4e27972c78ee980c1e6fd599cc47786850db2add/crates/agentgateway/proto/rbac.proto#L9-L20) with `CONTAINS `
```proto
message Rule {


  // The types of matchers which are supported.
  enum Matcher {
    // The value must be equal to the value in the claims.
    EQUALS = 0;

    // The value must be contained in the value in the claims.
    // This will only work for string/array values.
    CONTAINS = 1;
  }
```
 
- Generated protobuf code: [`go/api/rbac/rbac.pb.go`](https://github.com/agentgateway/agentgateway/blob/4e27972c78ee980c1e6fd599cc47786850db2add/go/api/rbac/rbac.pb.go#L32-L39) has only EQUALS enum
```
// Enum value maps for Rule_Matcher.
var (
	Rule_Matcher_name = map[int32]string{
		0: "EQUALS",
	}
	Rule_Matcher_value = map[string]int32{
		"EQUALS": 0,
	}
)

```
 
- OpenAPI yaml: [specification](https://github.com/agentgateway/agentgateway/blob/4e27972c78ee980c1e6fd599cc47786850db2add/crates/agentgateway/proto/openapi.yaml#L546-L567) contains a way different RBAC ruleset and rule definition

```
    RuleSet:
      type: object
      properties:
        name:
          type: string
          description: The name of the rule set.
        rules:
          type: array
          items:
            $ref: '#/components/schemas/Rule'
          description: The rules in the set.

    Rule:
      type: object
      properties:
        principal:
          type: string
          description: The principal to match.
        action:
          type: string
          enum: [allow, deny]
          description: The action to take.
```

### LINKED ISSUE #150: Ability to enable/disable an MCP server
Per client, we will want to expose/enable certain MCP servers and filter out others. Not just tools on a specific server, but the whole server itself.

### LINKED ISSUE #151: Error -32603: Failed to process response: HTTP error 500: Internal Server Error
Hi
I’m using the **Agent Gateway** with a custom **Flask agent** powered by **Gemini.**
- My Gemini Flask agent runs at: `http://localhost:8080`
- I configured an A2A listener on the Agent Gateway `host: localhost`, `port: 8000`

Here is my Flask POST request code:
```
@app.route("/", methods=["POST"])
def handle_request():
    try:
        data = request.get_json()
        print(">>> [INFO] FULL JSON received:",data)

        rpc_id = data.get("id")
        if not rpc_id:
            print(">>> [ERROR] No 'id' field in request!")
            return jsonify({
                "jsonrpc": "2.0",
                "id": None,
                "error": {
                    "code": -32600,
                    "message": "Missing 'id' field in JSON-RPC request"
                }
            }), 400

        params = data.get("params", {})
        message = params.get("message", {})
        parts = message.get("parts", [])

        user_input = ""
        if parts and isinstance(parts[0], dict):
            user_input = parts[0].get("text", "")

        if not user_input:
            return jsonify({
                "jsonrpc": "2.0",
                "id": rpc_id,
                "error": {
                    "code": -32602,
                    "message": "Missing or empty input"
                }
            }), 400

        response = model.generate_content(user_input)
        reply_text = getattr(response, "text", str(response))
        print(">>> [INFO] Gemini says:", reply_text)

        return jsonify({
            "jsonrpc": "2.0",
            "id": rpc_id,
            "result": {
                "message": {
                    "role": "agent",
                    "parts": [{"type": "text", "text": reply_text}]
                }
            }
        })

    except Exception as e:
        traceback.print_exc()
        return jsonify({
            "jsonrpc": "2.0",
            "id": data.get("id") if isinstance(data, dict) else None,
            "error": {
                "code": -32603,
                "message": "Internal Server Error",
                "data": str(e)
            }
        }), 500

 
```

Image

When I send a GET request to `http://localhost:8000/gemini-agent/.well-known/agent.json`
The `agent.json` file is served correctly from my Flask backend and is forwarded as expected by the Agent Gateway.

When I send a valid JSON-RPC POST request like this:
```
{
  "jsonrpc": "2.0",
  "id": "abc123",
  "method": "tasks/send",
  "params": {
    "id": "xyz",
    "message": {
      "role": "user",
      "parts": [
        { "type": "text", "text": "tell me a joke" }
      ]
    }
  }
}
```
to `http://localhost:8000/gemini-agent/` through UI or Postman

My Flask backend receives only this:
```
{
  "method": "tasks/send",
  "params": {
    "id": "xyz",
    "message": {
      "role": "user",
      "parts": [
        { "type": "text", "text": "tell me a joke" }
      ]
    }
  }
}
```

The `jsonrpc` and `id` fields are missing.

Because of this, my backend is not able to send a proper `JSON-RPC` response, and the frontend fails with a `500 Internal Server Error`.

The Agent Gateway seems to parse and reformat the body before sending it to the agent — removing top-level `jsonrpc` and `id` fields.
However, according to the JSON-RPC 2.0 spec, both id and jsonrpc must be included in requests and responses.

Image

Image

Am I missing something in my code or is it a bug in the build?

### LINKED ISSUE #154: Feature: RBAC for `tools/list` calls
Right now, RBAC protects the `tools/call` RPC. I think it would make sense to have it on `tools/list` RPC messages as well.

That way, available tools would be narrowed down based on claims in the token.

Thoughts?

### PR DESCRIPTION
**Pull request by howardjohn**
This PR introduces the next generation of Agentgateway building on the baseline MCP and A2A support to provide a full-fledge proxy supporting Kubernetes Gateway API, Inference Routing extension, and LLM consumption use cases.

For MCP:
* Update SDK fixing a variety of bugs
* Start of MCP auth support
* Upstream streamable HTTP support

For A2A:
* Update to v0.2 spec

Fixes https://github.com/agentgateway/agentgateway/issues/154
Fixes https://github.com/agentgateway/agentgateway/issues/151
Fixes https://github.com/agentgateway/agentgateway/issues/150
Fixes https://github.com/agentgateway/agentgateway/issues/149
Fixes https://github.com/agentgateway/agentgateway/issues/148
Fixes https://github.com/agentgateway/agentgateway/issues/144
Fixes https://github.com/agentgateway/agentgateway/issues/142

This PR unfortunately breaks the UI; a fix will be worked on ASAP

### CODE REVIEW

File: crates/agentgateway-app/src/main.rs [hunk 1]
```diff
@@ -0,0 +1,82 @@
+// Copyright Istio Authors
```
Comment (craigbox) [inline crates/agentgateway-app/src/main.rs]: There are a attributions from other projects throughout.  Given that you have changed these files, you might consider adding 

```
// Copyright agentgateway authors
```
(and/or solo.io) to the top of them all.

File: crates/agentgateway/proto/resource.proto [hunk 2]
```diff
@@ -7,6 +7,8 @@ import "google/protobuf/wrappers.proto";
 import "google/protobuf/any.proto";
```
Comment (npolshakova) [inline crates/agentgateway/proto/resource.proto:7]: Can we delete the old proto files (https://github.com/agentgateway/agentgateway/blob/4e27972c78ee980c1e6fd599cc47786850db2add/crates/agentgateway/proto/listener.proto), it looks like they're causing conflicts with the new Listener in resource.proto

File: crates/agentgateway/src/parse/transform.rs [hunk 3]
```diff
@@ -0,0 +1,159 @@
...
+		if !encode_buffer.is_empty() {
+			let data = encode_buffer.split_to(encode_buffer.len());
+			return Poll::Ready(Some(Ok(http_body::Frame::data(data.freeze()))));
+		}
+
+		// We need more input data - poll the underlying body
+		let res = ready!(this.body.as_mut().poll_frame(cx));
+		match res {
+			(Some(Ok(frame))) => {
+				if let Some(data) = frame.data_ref() {
```
Comment (yuval-k) [inline crates/agentgateway/src/parse/transform.rs:133]: if this is trailers, would they get lost?

File: examples/openapi/README.md [hunk 4]
```diff
@@ -9,39 +9,23 @@ This example will show you how to proxy the [Swagger Petstore](https://petstore3
...
-          "schema": {
-            "file_path": "examples/openapi/openapi.json"
-          }
-        }
-      }
-    ]
-  }
+```yaml
+name: openapi
+openapi:
```
Comment (christian-posta) [inline examples/openapi/README.md:19]: this doesn't look right. I think we should have the complete mcp backend. I think it's like this?

```yaml
      - mcp:
          name: openapi
          targets:
          - name: petstore
            openapi:
              schema:
                file: ./examples/openapi/openapi.json   # or use 'remote_schema' for a URL
              host: localhost
              port: 8080
```

File: examples/openapi/README.md [hunk 5]
```diff
@@ -9,39 +9,23 @@ This example will show you how to proxy the [Swagger Petstore](https://petstore3
...
+  schema:
+    file: ./examples/openapi/openapi.json
+  host: localhost
+  port: 8080
 ```
 
+This will expose each method in the openapi specification as MCP tools, and proxy them to the petstore application (on `localhost:8080`).
+
```
Comment (christian-posta) [inline examples/openapi/README.md:27]: Seems the images are outdated. I don't think that should hold up the PR. I can PR those later. But I noticed that in the inspector, it doesn't seem to understand the fields for the REST APIs that get exposed as tools. That is, I cannot enter any values in for the parameters.

File: crates/agentgateway/proto/resource.proto (hunk 2 above)
Comment (howardjohn) [reply crates/agentgateway/proto/resource.proto:7]: These should be deleted (in first commit they weren't so maybe this was looking there?)

File: crates/agentgateway/src/mcp/rbac.rs [hunk 6]
```diff
@@ -0,0 +1,273 @@
...
+			},
+			None => None,
+		}
+	}
+}
+
+lazy_static! {
+	static ref PRINCIPAL_UID_ANONYMOUS: EntityUid = "AnonymousUser::\"\"".parse().unwrap();
+	static ref PRINCIPAL_NAME_USER: EntityTypeName = "User".parse().unwrap();
+	static ref ACTION_CALL_TOOL: EntityUid = r#"Action::"call_tool""#.parse().unwrap();
```
Comment (christian-posta) [inline crates/agentgateway/src/mcp/rbac.rs:264]: So "Action" call_tool makes sense for specifying policy around tools. But It seems we have other resource targets beyond tools, like Prompt:: and Resource:: ? Should this be "call_tool" or just "call" ?.

File: crates/agentgateway/src/parse/transform.rs (hunk 3 above)
Comment (howardjohn) [reply crates/agentgateway/src/parse/transform.rs:133]: You are probably the only person I know that can find a bug like this in a 45k line PR :laughing: . Definitely correct, I added a test and a fix

File: examples/openapi/README.md (hunk 4 above)
Comment (howardjohn) [reply examples/openapi/README.md:19]: this was just showing the important part of the `config.yaml` -- the real config is in config.yaml. Which was also wrong, but I just fixed!

File: crates/agentgateway/src/mcp/rbac.rs (hunk 6 above)
Comment (howardjohn) [reply crates/agentgateway/src/mcp/rbac.rs:264]: So we have

get/list prompt
read/list resource
call/list tools

maybe our action types are "read", "call", and "list"?

File: examples/authorization/config.yaml [hunk 7]
```diff
@@ -0,0 +1,30 @@
...
+            # Relative to the folder the binary runs from, not the config file
+            file: ./manifests/jwt/pub-key
+        mcpAuthorization:
+          rules:
+          # Allow anyone to call 'echo'
+          - 'permit(principal, action == Action::"call_tool", resource == Tool::"echo");'
+          # Only the test-user can call 'add'
+          - 'permit(principal == User::"test-user", action == Action::"call_tool", resource == Tool::"add");'
+          # Any authenticated user with the claim `nested.key == value` can access 'printEnv'
+          - |
```
Comment (linsun) [inline examples/authorization/config.yaml:20]: sorry new to this, does this indicate "or"?  I noticed the other 2 permits don't have it.

Comment (howardjohn) [reply examples/authorization/config.yaml:20]: This is a yaml multiline string :slightly_smiling_face: 

The semantics of multiple policies is just like istio, `if any deny then deny, if any allow then allow, else deny`. (note: there is a `deny` I just don't have an example here)

File: crates/agentgateway/proto/resource.proto (hunk 2 above)
Comment (npolshakova) [reply crates/agentgateway/proto/resource.proto:7]: I think it's still in the go generated files: https://github.com/howardjohn/agentgateway/tree/next/go/api (which doesn't get cleaned up by the make target). I think removing the `go/api/*`files and running `make generate-apis` should fix it.

File: examples/authorization/config.yaml (hunk 7 above)
Comment (linsun) [reply examples/authorization/config.yaml:20]: Ah thanks! :)

File: crates/agentgateway/src/mcp/rbac.rs (hunk 6 above)
Comment (christian-posta) [reply crates/agentgateway/src/mcp/rbac.rs:264]: yeah that makes sense

**Review by EItanya — APPROVED** [review]
